# Generated by Django 4.1.7 on 2023-02-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IHA",
            fields=[
                ("ihaID", models.AutoField(primary_key=True, serialize=False)),
                ("ihaName", models.CharField(max_length=50)),
                ("ihaType", models.CharField(max_length=50)),
                ("ihaCommunicationRange", models.IntegerField()),
                ("ihaHover", models.CharField(max_length=50)),
                ("ihaLength", models.CharField(max_length=50)),
                ("ihaWingSpan", models.CharField(max_length=50)),
                ("ihaMaxSpeed", models.CharField(max_length=50)),
                ("ihaMaxAltitude", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "iha",
            },
        ),
    ]
