# Generated by Django 4.1.7 on 2023-02-26 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baykar", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="iha",
            name="ihaType",
        ),
    ]
