# Generated by Django 4.1.7 on 2023-02-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baykar", "0002_remove_iha_ihatype"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
