# Generated by Django 4.1.7 on 2023-02-26 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baykar", "0004_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="user",
        ),
    ]
